### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by jaylinski** [dettmering/hugo-build#1]
Hi!

I just wanted to notify you that the docker builds are currently failing: https://hub.docker.com/r/dettmering/hugo-build/builds/

(Thx for providing this image! :octocat:)

**Comment by jaylinski** [comment]
Will be resolved by https://github.com/dettmering/hugo-build/pull/2.

**Comment by dettmering** [comment]
Hi, thank you, someone fixed it and I've merged the changes back.
